version: "3.8"
services:
  frontend:
    build: ./frontend
    ports: 
      - "8080:8080"
  app:
    build: ./backend
    ports: 
      - 3000:3000
    env_file: .env
    depends_on: 
      - db
  db:
    image: postgres:10.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports: 
      - 5432
    volumes: 
      - db-data:/var/lib/postgresql/data
volumes: 
  db-data:
  